# -*- coding: utf-8 -*-
"""David-pertemuan2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11oXtfh0slUSsLmu-gdQibPA3TuoUtEph
"""

nama = input("masukan nama anda:")
NIM = input("masukan NIM anda:")
print("Nama anda adalah",nama,NIM)

def getFirst(myList):
  return(myList[2])
  getFirst([1,2,3])

def getLast(myList):
    return myList[-1]

result = getLast([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(result)

def getSum(angka_set):
    return sum(angka_set)

def subtractSets(set1, set2):
    sum_set1 = getSum(set1)
    sum_set2 = getSum(set2)

    return sum_set1 - sum_set2

set1 = {3, 5, 8}
set2 = {2, 4}

hasil_pengurangan = subtractSets(set1, set2)
print(f"Hasil pengurangan: {hasil_pengurangan}")

def getSum(himpunan):
    return sum(himpunan)

def divideSets(set1, set2):

    total_set1 = getSum(set1)
    total_set2 = getSum(set2)

    if total_set2 == 0:
        return "Tidak bisa membagi dengan nol"

    return total_set1 / total_set2

himpunan1 = {10, 20, 30}
himpunan2 = {5, 15}

hasil = divideSets(himpunan1, himpunan2)
print(f"Hasil pembagian: {hasil}")

def getSum(mylist):
    sum = 1
    for item in mylist:
       sum *= item
    return sum
getSum([1,2,3,4])

def getSum(mylist):
    sum = 1
    for item in mylist:
       sum /= item
    return sum
getSum([1,2,3,4])